### ISSUE TITLE
Melodic release

### ISSUE THREAD

**Issue by artivis** [AndreaCensi/csm#29]
As of today there isn't a release of csm for ROS Melodic.  
Would it be possible to release it ?

**Comment by 130s** [comment]
Done in https://github.com/CCNYRoboticsLab/scan_tools/issues/67

**Comment by 130s** [comment]
> Done in [CCNYRoboticsLab/scan_tools#67](https://github.com/CCNYRoboticsLab/scan_tools/issues/67)

I'm sorry, the linked issue was of downstream repo.

That said, it's tracked in https://github.com/ros-gbp/csm-release/issues/4 and it's done.
