### ISSUE TITLE
Create a release tag?

### ISSUE THREAD

**Issue by 130s** [AndreaCensi/csm#9]
Thank you for making the great tool opensourced!

ROS wrapper of CSM, [laser_scan_matcher](http://wiki.ros.org/laser_scan_matcher) downloads source code of CSM during build process. Right now it downloads by specifying the checksum of a commit. This may make us ponder which commit we should aim, when there are newer commits happen on CSM(*1). If there's a release tag in CSM, it's much easier on ROS end to just point to it.

Would you consider tagging a release?

*1 Currently laser_scan_matcher points to the commit in 2010. Ref. https://github.com/ccny-ros-pkg/scan_tools/pull/29

Thank you again.

**Comment by AndreaCensi** [comment]
Hi Issac ---

I will add you as a contributor to the repository. In this way you can add/modify release tags, add manifest files, etc. 

A.

**Comment by k-okada** [comment]
hi, as we discussed in 
https://github.com/AndreaCensi/csm/pull/13#issuecomment-153556065, 
releasing csm_eigen branch was not correct, so could you add new tag to current master?

**Comment by k-okada** [comment]
when you release new version please update version number at https://github.com/AndreaCensi/csm/blob/master/package.xml#L4 too

**Comment by k-okada** [comment]
Sorry for confusion, but I think another option is to  go into 
http://wiki.ros.org/bloom/Tutorials/ReleaseThirdParty#Modifying_the_Release_Repository
option, if adding / deleting package.xml confusing maintainer and just messes the repository.

**Comment by k-okada** [comment]
ok, released in https://github.com/ros/rosdistro/pull/9785
we no longer using package.xml in this repo, but use https://github.com/tork-a/csm-release/tree/master/patches
we also need some patches https://github.com/tork-a/csm-release/blob/patches/release/indigo/csm/0001-fix-for-compile-error-http-stackoverflow.com-questio.patch, this may because of strict option in compile time.

- we no longer need package.xml in this repo
- adding tag as 1.0.2 to HEAD master may help, but not required.

**Comment by 130s** [comment]
> adding tag as 1.0.2 to HEAD master may help, but not required.

[Done](https://github.com/AndreaCensi/csm/releases/tag/1.0.2).

Is using `package.xml` from release repository (i.e. not from devel repository https://github.com/AndreaCensi/csm) permanent @k-okada ?

**Comment by 130s** [comment]
> we also need some patches https://github.com/tork-a/csm-release/blob/patches/release/indigo/csm/0001-fix-for-compile-error-http-stackoverflow.com-questio.patch, this may because of strict option in compile time.

Note: To apply the above patch upon making a ROS Jade release, I did [Porting patches from one rosdistro to another](http://wiki.ros.org/bloom/Tutorials/ReleaseThirdParty#Porting_patches_from_one_rosdistro_to_another) to port the patch from older distro (Indigo).
